# Dang-PC setup
monitor= desc:Microstep MSI MP243 PB5H113601128, preferred, auto-right, 1
monitor= desc:ViewSonic Corporation VX2479 Series X9N234600303, 1920x1080@140, 0x0, 1
# monitor= HDMI-A-1, disable

# Laptop
# monitor= eDP-1, 1920x1080@60,0x0, 1.25
